name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt update && sudo apt install build-essential -y

      - name: Build C backend
        run: gcc calc/test_calculator.c calc/calculator.c -o test_c

      - name: Run C tests
        run: ./test_c

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build and install Python module
        run: |
          python setup.py build
          python setup.py install

      - name: Run Python tests
        run: python -m unittest discover -s tests

      - name: Run black (Python formatter)
        run: |
          pip install black
          black --check .

      - name: Run pylint (Python linter)
        run: |
          pip install pylint
          pylint $(wildcard *.py) tests/*.py

      - name: Run clang-format (C formatter check)
        run: |
          sudo apt install clang-format -y
          clang-format --dry-run --Werror calc/*.c calc/*.h python_bindings/*.c

      - name: Run cppcheck (C static analyzer)
        run: |
          sudo apt install cppcheck -y
          cppcheck --enable=all --error-exitcode=1 calc python_bindings